theme: jekyll-theme-cayman
markdown: GFM
title: Implementing BDI Continual Temporal Planning for Robotic Agents
description: Alex Zanetti, Devis Dal Moro, Redi Vreto, Marco Robol, Marco Roveri and Paolo Giorgini
